apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-mysql
  minReplicas: 1
  maxReplicas: 100
  minReadySeconds: 5
  targetCPUUtilizationPercentage: 5
